services:
  - type: web
    name: semental-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --config gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_ORIGIN
        sync: false
      - key: WEB_CONCURRENCY
        value: 4
      - key: TIMEOUT
        value: 30
      - key: LOG_LEVEL
        value: info
    disk:
      name: model
      mountPath: /opt/render/project/src/model
      sizeGB: 1 