services:
  - type: web
    name: semental-api
    env: python
    runtime: python3.11
    buildCommand: |
      pip install -r requirements.txt
      
      # Create necessary directories
      mkdir -p /opt/render/project/src/model
      
      # Copy the model files with verbose output
      echo "Current directory contents:"
      ls -la
      
      echo "Copying model files..."
      if [ -f model.mdl ]; then
        cp -v model.mdl /opt/render/project/src/model/model.mdl
      else
        echo "Error: model.mdl not found in current directory"
        exit 1
      fi
      
      if [ -f words.txt ]; then
        cp -v words.txt /opt/render/project/src/words.txt
      else
        echo "Error: words.txt not found in current directory"
        exit 1
      fi
      
      # Verify files exist and have size
      echo "Verifying copied files..."
      if [ ! -s /opt/render/project/src/model/model.mdl ]; then
        echo "Error: model.mdl is missing or empty at destination"
        ls -la /opt/render/project/src/model/
        exit 1
      fi
      
      if [ ! -s /opt/render/project/src/words.txt ]; then
        echo "Error: words.txt is missing or empty at destination"
        ls -la /opt/render/project/src/
        exit 1
      fi
      
      echo "Model files copied successfully"
      echo "Final directory structure:"
      ls -R /opt/render/project/src/
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_ORIGIN
        sync: false
      - key: WEB_CONCURRENCY
        value: 4
      - key: TIMEOUT
        value: 30
      - key: LOG_LEVEL
        value: info
      - key: PORT
        value: 10000
      - key: MODEL_PATH
        value: /opt/render/project/src/model/model.mdl
      - key: WORDS_PATH
        value: /opt/render/project/src/words.txt
    disk:
      name: model
      mountPath: /opt/render/project/src/model
      sizeGB: 1 