services:
  - type: web
    name: semental-api
    env: python
    runtime: python3.11
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p /opt/render/project/src/model
      
      # Function to download large files from Google Drive
      download_from_gdrive() {
        FILEID=$1
        FILENAME=$2
        
        # Get the confirmation token
        CONFIRM=$(curl -sL "https://drive.google.com/uc?export=download&id=${FILEID}" | grep -o 'confirm=[^&]*' | cut -d'=' -f2)
        
        # Download with confirmation token
        curl -L -o "$FILENAME" "https://drive.google.com/uc?export=download&confirm=${CONFIRM}&id=${FILEID}"
      }
      
      echo "Downloading syn1neg file..."
      download_from_gdrive "1ubP3YTB_9CuZ84Iey0WuR8Mru-oDtD3N" "/opt/render/project/src/model/model.mdl.syn1neg.npy"
      
      echo "Downloading vectors file..."
      download_from_gdrive "1pB9Ht2owUreXjejfwoIrsNQiFcdMEVZf" "/opt/render/project/src/model/model.mdl.wv.vectors.npy"
      
      # Verify files exist and have size
      if [ ! -s /opt/render/project/src/model/model.mdl.syn1neg.npy ]; then
        echo "syn1neg file is empty or missing"
        exit 1
      fi
      
      if [ ! -s /opt/render/project/src/model/model.mdl.wv.vectors.npy ]; then
        echo "vectors file is empty or missing"
        exit 1
      fi
      
      echo "Model files downloaded successfully"
      cp model/* /opt/render/project/src/model/
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_ORIGIN
        sync: false
      - key: WEB_CONCURRENCY
        value: 4
      - key: TIMEOUT
        value: 30
      - key: LOG_LEVEL
        value: info
      - key: PORT
        value: 10000
      - key: MODEL_PATH
        value: /opt/render/project/src/model/model.mdl
      - key: WORDS_PATH
        value: /opt/render/project/src/words.txt
    disk:
      name: model
      mountPath: /opt/render/project/src/model
      sizeGB: 1 