services:
  - type: web
    name: semental-api
    env: python
    runtime: python3.11
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p /opt/render/project/src/model
      
      # Copy the model files
      echo "Copying model files..."
      cp -v model/model_small.bin /opt/render/project/src/model/
      
      # Verify files exist and have size
      if [ ! -s /opt/render/project/src/model/model_small.bin ]; then
        echo "Error: model_small.bin is missing or empty"
        exit 1
      fi
      
      echo "Model files copied successfully"
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_ORIGIN
        sync: false
      - key: WEB_CONCURRENCY
        value: 4
      - key: TIMEOUT
        value: 30
      - key: LOG_LEVEL
        value: info
      - key: PORT
        value: 10000
      - key: MODEL_PATH
        value: /opt/render/project/src/model/model_small
      - key: WORDS_PATH
        value: /opt/render/project/src/words.txt
    disk:
      name: model
      mountPath: /opt/render/project/src/model
      sizeGB: 1 